apiVersion: apps/v1
kind: Deployment
metadata:
  name: donationcenter
  labels:
    app: donationcenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: donationcenter
  template:
    metadata:
      labels:
        app: donationcenter
    spec:
      containers:
        - name: donationcenter
          image: username/donationcenter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5