apiVersion: apps/v1
kind: Deployment
metadata:
  name: donation
  labels:
    app: donation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: donation
  template:
    metadata:
      labels:
        app: donation
    spec:
      containers:
        - name: donation
          image: username/donation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5