apiVersion: apps/v1
kind: Deployment
metadata:
  name: unicef
  namespace: coffee
  labels:
    app: unicef
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unicef
  template:
    metadata:
      labels:
        app: unicef
    spec:
      containers:
        - name: unicef
          image: kccuser13.azurecr.io/unicef:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5